export * from './client.js';
export * from './vector.js';

// Re-export generated types and enums so consumers depend on @akp/db rather
// than reaching into @prisma/client directly.
export type {
  Organization,
  User,
  Membership,
  Session,
  ApiKey,
  Invite,
  DataSource,
  Document,
  DocumentChunk,
  DocumentVersion,
  DocumentAcl,
  Conversation,
  Message,
  Citation,
  IngestionJob,
  Evaluation,
  EvaluationResult,
  UsageEvent,
  AuditLog,
  WebhookEndpoint,
  WebhookDelivery,
  MessageFeedback,
  IdempotencyKey,
  Team,
  TeamMembership,
  Collection,
  CollectionDocument,
  PromptTemplate,
  StoredObject,
  SsoConnection,
  ScimToken,
  Subscription,
  BudgetPeriod,
  ToolInvocation,
} from '@prisma/client';

export {
  Role,
  OrganizationStatus,
  UserStatus,
  MembershipStatus,
  ApiKeyStatus,
  DataSourceType,
  DataSourceStatus,
  DocumentStatus,
  JobType,
  JobStatus,
  MessageRole,
  EvaluationStatus,
  UsageKind,
  WebhookEndpointStatus,
  WebhookDeliveryStatus,
  FeedbackRating,
  FeedbackReason,
  IdempotencyStatus,
  AclSubjectType,
  AclPermission,
  CollectionVisibility,
  SsoProvider,
  SubscriptionStatus,
  ToolSideEffect,
  ToolInvocationStatus,
} from '@prisma/client';
