/**
 * Stable, machine-readable error codes returned to API clients.
 *
 * These are part of the platform's public contract: SDKs, the frontend, and
 * customer integrations branch on them. Treat renames/removals as breaking
 * changes. Human-readable messages may change freely; codes may not.
 */
export const ErrorCode = {
  // --- Client / validation (4xx) ---
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  TOKEN_INVALID: 'TOKEN_INVALID',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',
  INSUFFICIENT_SCOPE: 'INSUFFICIENT_SCOPE',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  IDEMPOTENCY_CONFLICT: 'IDEMPOTENCY_CONFLICT',
  RATE_LIMITED: 'RATE_LIMITED',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  // Auth hardening
  MFA_REQUIRED: 'MFA_REQUIRED',
  MFA_INVALID: 'MFA_INVALID',
  // AI / safety
  PROMPT_INJECTION_DETECTED: 'PROMPT_INJECTION_DETECTED',
  CONTENT_BLOCKED: 'CONTENT_BLOCKED',

  // --- Server / infrastructure (5xx) ---
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
  DEPENDENCY_FAILURE: 'DEPENDENCY_FAILURE',

  // --- Domain-specific ---
  ORGANIZATION_SUSPENDED: 'ORGANIZATION_SUSPENDED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  BUDGET_EXCEEDED: 'BUDGET_EXCEEDED',
  FEATURE_DISABLED: 'FEATURE_DISABLED',
  ENCRYPTION_ERROR: 'ENCRYPTION_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
